### ISSUE TITLE
Query Parameters in URL

### ISSUE THREAD

**Issue by lmangani** [metrico/cloki-view#11]
High Priority: 

cloki-view should accept all key query parameters in URL _(ie: url?query=x&limit=10&start=1234568790...)_ and update the URL on each modifications to allow links to be copy-pasted and embedding

The Remote LogQL API should also be allowed as parameter (and probably displayed in the top bar as editable)

**Comment by jacovinus** [comment]
- [ ]  get parameters from query params

- [ ] update query params when update parameters

- [ ] get ur with query params when "Share Link" button is pressed

- [ ] store url parameters as "search history"

**Comment by Dletta** [comment]
I split https://github.com/metrico/cloki-view/issues/11 into it's own issue, so PR #25 can be finished sooner

**Comment by Dletta** [comment]
Closed in PR #25
