### ISSUE TITLE
Expand time-range options

### ISSUE THREAD

**Issue by AlexeyOplachko** [metrico/cloki-view#21]
- [x] Add additional presets for time-ranges
- [x] Implement "text-based" display of currently selected preset. I.e. "Today" instead of 2022/2/7 00:00:00 - 2022/2/7 23:59:59
- [x] Restore time-range from previous sessions

**Comment by jacovinus** [comment]
**add quick ranges**

- last 5 minutes
- last 15 minutes
- last 30 minutes
- last 3 hours
- last 6 hours
- last 12 hours
- last 24 hours

**Comment by Dletta** [comment]
closed with PR #27
