### ISSUE TITLE
check for screen sizes and status bar inputs breakpoints

### ISSUE THREAD

**Issue by jacovinus** [metrico/cloki-view#26]
- on reducing screen size the inputs of the status bar breaks

**Comment by Dletta** [comment]
Closed, not an issue in latest version

**Comment by AlexeyOplachko** [comment]
🤔 still breaks for me 
![image](https://user-images.githubusercontent.com/45398541/157204438-578a73f1-0699-4ee1-9907-7af79ae3862b.png)
