### ISSUE TITLE
Label selector size overflow

### ISSUE THREAD

**Issue by AlexeyOplachko** [metrico/cloki-view#34]
If labels are bigger than screen width they go out of bounds of the screen. 
![image](https://user-images.githubusercontent.com/45398541/154487377-695298fc-efb4-4653-a058-67840491b4a2.png)

**Comment by jacovinus** [comment]
Issue was solved with pull request #36, 
@AlexeyOplachko 's Solution:
- limited size of labels
- added tooltips for larger entries than label width limit.

**closing**
