### ISSUE TITLE
Search Improvements

### ISSUE THREAD

**Issue by lmangani** [metrico/cloki-view#4]
The following improvements would greatly benefit the search experience:

- [x] Allow SHIFT+ENTER  / CTRL+ENTER to submit the search form
- [x] Scroll to Top/Reset results view on new Search

**Comment by Dletta** [comment]
Split out Search History to #29

**Comment by jacovinus** [comment]
Reset results on new search done.
left: 
- Scroll to top

**Comment by jacovinus** [comment]
fixed cleaning screen on new search, closing
