### ISSUE TITLE
Log Label Filters

### ISSUE THREAD

**Issue by lmangani** [metrico/cloki-view#5]
Log Label filters should be available next to log tabs to extend the query labels object interactively:

#### Example
[ + ] = adds `level="Debug"`
[ - ] = adds `level!="Debug"`
#### Screenshot
![image](https://user-images.githubusercontent.com/1423657/152549501-22bb312a-ab00-40ee-93dc-e52c954189dd.png)

The mechanism is simply a variation of the existing Label / Value selector

**Comment by jacovinus** [comment]
continues at #56 , closing
