### ISSUE TITLE
Manually removing label does not update state

### ISSUE THREAD

**Issue by Dletta** [metrico/cloki-view#56]
Steps to recreate issue:
1. make a regular query, ie: type = clickhouse
2. open a log and choose + on the PID
3. remove the PID manually from the query, enter
4. open a random log, and pick another tag (ie: level) - the PID will reappear

**Comment by AlexeyOplachko** [comment]
It happens with any way to add new labels to query, not only with +/- thing 
You can check by choosing two values from selector, then removing one by editing query. Any interaction that calls query builder returns whatever you removed.

**Comment by lmangani** [comment]
query execution should always reset any select state of the builder to the actual tags submitted

**Comment by jacovinus** [comment]
**done:** 
- query execution should always reset any select state of the builder to the actual tags submitted
- The values now selects on visible lists at every query execution if matches label / value
- fixed exclusive selection of tags inside curly braces
